parameters:
#    siverra_vcard.example.class: LilaConcepts\SiverraVcardBundle\Example

services:
#    siverra_vcard.example:
#        class: %siverra_vcard.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
